name: "statime"
version: "edge"
slug: statime
description: >-
  Export a PTP clock for spin2dante and inferno-based Dante tools.
url: "https://github.com/salanki/spin2dante"
stage: experimental
startup: system
boot: auto
init: false
host_network: true
legacy: true
arch:
  - aarch64
  - amd64
image: ghcr.io/salanki/spin2dante-statime-addon
map:
  - type: share
    read_only: false
    path: /share
privileged:
  - SYS_TIME
options:
  ptp_interface: "auto"
  clock_path: "/share/usrvclock"
  log_level: "info"
schema:
  ptp_interface: str
  clock_path: str
  log_level: list(trace|debug|info|warn|error)
